steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'europe-west12-docker.pkg.dev/products-microservices-426815/image-registry/products-ms',
        '-f',
        'dockerfile.prod',
        '--platform=linux/amd64',
        '.',
      ]
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'europe-west12-docker.pkg.dev/products-microservices-426815/image-registry/products-ms',
      ]
options:
  logging: CLOUD_LOGGING_ONLY
